version: '3'

services:
  app:
    image: ghcr.io/rajkumaar23/playstore-api:main
    container_name: playstore-api-app
    restart: always
    environment:
      - REDIS_ADDRESS=redis:6379
      - SERVER_PORT=5003
      - GIN_MODE="release"
      - DEFAULT_GL="US"
    ports:
      - "5003:5003"
    depends_on:
      - redis
    networks:
      - playstore-api-network

  redis:
    image: redis:latest
    container_name: playstore-api-redis
    restart: always
    networks:
      - playstore-api-network

networks:
  playstore-api-network:
    driver: bridge
